б 24
haxnted/pet-family-backend pull request #51
Opened 2024-10-30 12:49 UTC by haxnted

2024-10-31 08:15 UTC, KirillSachkov requested changes

2024-10-31 08:15 UTC, KirillSachkov commented on PetFamily.Backend/src/Discussion/PerFamily.Discussion.Application/IDiscussionUnitOfWork.cs
> +public interface IDiscussionUnitOfWork
UnitOfWork нужно зарегистрировать один для всех модулей, а инжектить его через keyedscoped и вызывать через ключ по Enum

2024-10-31 08:15 UTC, KirillSachkov commented on PetFamily.Backend/src/VolunteerRequest/PetFamily.VolunteerRequest.Domain/ValueObjects/VolunteerInformation.cs
> +public class VolunteerInformation
это должнен быть VO со всей валидацией и тд, нужно сделать богатые доменные модели

2024-11-01 07:41 UTC, haxnted commented on PetFamily.Backend/src/VolunteerRequest/PetFamily.VolunteerRequest.Domain/ValueObjects/VolunteerInformation.cs
> +public class VolunteerInformation
Не совсем понял, что можно тут валидировать, если к нам на вход поступают уже валидные объекты.

2024-11-01 07:44 UTC, haxnted commented on PetFamily.Backend/src/Discussion/PerFamily.Discussion.Application/IDiscussionUnitOfWork.cs
> +public interface IDiscussionUnitOfWork
хорошо, я создам ветку с рефакторингом и везде поправлю

2024-11-01 07:55 UTC, KirillSachkov approved these changes

2024-11-01 07:55 UTC, KirillSachkov commented on PetFamily.Backend/src/VolunteerRequest/PetFamily.VolunteerRequest.Domain/ValueObjects/VolunteerInformation.cs
> +public class VolunteerInformation
сори, не увидел, апрув

2024-11-01 07:55 UTC, merged